services:
  financialtracker.services.authorizeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5010
    
    ports:
      - "5010:5010"
  financialtracker.services.analytics:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5030
    ports:
      - "5030:5030"
