<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <RootNamespace>FinancialTracker.Services.Analytics</RootNamespace>
        <DockerComposeProjectPath>../docker-compose.dcproj</DockerComposeProjectPath>
        <UserSecretsId>09b17bc5-9515-4cd9-b4fe-8580d12d259b</UserSecretsId>
        <LangVersion>12</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
    <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
    <ItemGroup>
        <PackageReference Include="AutoMapper" Version="14.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\MessageBus.Shared\MessageBus.Shared.csproj" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="DataAccess\Migrations\" />
    </ItemGroup>

</Project>
